### ISSUE TITLE
don't remove aidungeon support

### ISSUE THREAD

**Issue by Ghost-Bit** [d4n3436/Fergun#10]
the other bot isn't working, and i don't think the one in the actual AID server is public so this would be killing off an already scarce supply of bots that do this

**Comment by d4n3436** [comment]
I've already made a decision, sorry.
If you want to keep using AI Dungeon, I recommend self-hosting the bot. The source code of Fergun v1 is available [here](https://github.com/d4n3436/Fergun/tree/v1).
No support for this version nor for non-official instances of Fergun will be given.
